""" updating the tables

Revision ID: 79899b882253
Revises: dac51c9156b7
Create Date: 2021-05-04 10:32:21.556858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79899b882253'
down_revision = 'dac51c9156b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'feature_image')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'profile_pic_path',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'profile_pic_path',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('blogs', sa.Column('feature_image', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
